export default {
	id: "akli",
	title: "AKLÌ SORTER",
	songs: [
        "Tame",
        "Daylight",
        "Duplicity",
        "Robot",
        "Taika",
        "Baimė",
        "Pastovu",
        "Karma",
        "Arčiau",
        "Skauda",
        "Šventi",
        "Lengvai",
        "Pabaiga",
        "Nuobodu",
        "Vieną",
        "Silpna",
        "Skęsti",
        "Outro",
        "Švari sąžinė",
        "Aštriausiu peiliu",
        "Kvėpuoju tamsa",
        "Netikra",
        "Dugnas",
        "Vaidenas",
        "Kaina",
        "III",
        "Labanakt",
        "Save laikau",
        "Pabodo, matyt",
        "D.I.E",
        "Per saldu",
        "ŽGŽ",
        "Morfinas"
    ],
};
