export default {
	id: "katarsis",
	title: "KATARSIS SORTER",
	songs: [
		"Niekas",
		"Vasarą galvoj minoras",
		"Spengia Galvoje",
		"Siluetai",
		"Rasa",
		"DES",
		"Lapų šlamesiai išblaškė miegą",
		"Ėda",
		"Būsi",
		"Praradau tave",
		"Paleisiu (Dausos)",
		"Pamiršau žiūrėt į paukščius",
		"Tyla",
		"Nebeturiu jėgų",
		"Ji netikra",
		"Dingo",
		"Tavo Akys (Choir Version)",
		"Balta Meilė",
		"Paleisiu",
		"Išliesiu",
		"Dega",
		"Žiedlapis tau",
		"Likę tik randai",
		"Kada",
		"Laikei tu mane",
		"Neleisk man",
		"Malda",
		"Tavo Akys",
		"Kas man be jūros",
		"Nebepaleidžia",
		"Surasiu"
	],
};
